# credential-pattern: 1Password-backed API credential management
# Source this file in your .zshrc or .bashrc
#
# Prerequisites:
#   - 1Password CLI (`op`) installed and authenticated
#   - Items stored with category "API Credential" and field "credential"
#   - Optional: tag items with "cli:<toolname>" for auto-aliased `op run` wrappers

# Where the generated secrets file lives
CREDENTIAL_PATTERN_SECRETS="${CREDENTIAL_PATTERN_SECRETS:-$HOME/.zshrc_op_secrets}"

# Default vault for personal credentials
CREDENTIAL_PATTERN_VAULT="${CREDENTIAL_PATTERN_VAULT:-Personal}"

function api() {
  case "$1" in
    get)
      # Read a credential value
      # Usage: api get <item_name> [field_name]
      op read "op://${CREDENTIAL_PATTERN_VAULT}/${2}/${3:-credential}"
      ;;

    set)
      # Create or update a credential
      # Usage: api set <item_name> <value>
      if [[ -z "$2" || -z "$3" ]]; then
        echo "Usage: api set <name> <value>" >&2
        return 1
      fi
      if op item get "$2" --vault="$CREDENTIAL_PATTERN_VAULT" &>/dev/null; then
        op item edit "$2" --vault="$CREDENTIAL_PATTERN_VAULT" "credential=$3"
      else
        op item create --category="API Credential" --title="$2" --vault="$CREDENTIAL_PATTERN_VAULT" "credential=$3"
      fi
      ;;

    del)
      # Delete a credential (with confirmation)
      # Usage: api del <item_name>
      if [[ -z "$2" ]]; then
        echo "Usage: api del <name>" >&2
        return 1
      fi
      echo -n "Delete API credential '$2'? [y/N] "
      read -r confirm
      [[ "$confirm" =~ ^[Yy]$ ]] && op item delete "$2" --vault="$CREDENTIAL_PATTERN_VAULT" && echo "Deleted." || echo "Aborted."
      ;;

    update)
      # Regenerate the secrets file from 1Password
      # Exports op:// references for all API Credential items
      # Generates `op run` aliases for items tagged with cli:<toolname>
      local out="$CREDENTIAL_PATTERN_SECRETS"
      echo "Fetching API credentials from 1Password (vault: $CREDENTIAL_PATTERN_VAULT)..."
      local items_json
      items_json=$(op items list --vault="$CREDENTIAL_PATTERN_VAULT" --categories "API Credential" --format json) || return 1
      {
        echo "# Auto-generated by 'api update' — do not edit manually"
        echo "# Last updated: $(date)"
        echo "# Vault: $CREDENTIAL_PATTERN_VAULT"
        echo ""
        echo "# Secret references (resolved at runtime by 'op run')"
        echo "$items_json" | jq -r '.[] | "export \(.title)=\"op://'"$CREDENTIAL_PATTERN_VAULT"'/\(.title)/credential\""'
        echo ""
        echo "# Tool aliases (op run wrappers, derived from cli: tags in 1Password)"
        echo "$items_json" | jq -r '[.[] | .tags[]? | select(startswith("cli:")) | ltrimstr("cli:")] | unique[] | "alias \(.)='"'"'op run -- \(.)'"'"'"'
      } > "$out"
      echo "Written to $out — run 'source $out' or restart your shell."
      ;;

    token)
      # Generate a scoped service account token for automation
      # Usage: api token <vault> [hours]
      # Returns a short-lived, read-only token for the specified vault
      local vault="${2}"
      local hours="${3:-8}"
      if [[ -z "$vault" ]]; then
        echo "Usage: api token <vault> [hours]" >&2
        echo "  Generates a short-lived service account token scoped to <vault>" >&2
        echo "  Default expiry: 8 hours" >&2
        return 1
      fi
      local token_name="api-token-$(date +%s)"
      echo "Creating service account token for vault '$vault' (expires in ${hours}h)..." >&2
      local token
      token=$(op service-account create "$token_name" \
        --vault "${vault}:read_items" \
        --expires-in "${hours}h" \
        --raw) || return 1
      echo "$token"
      echo "" >&2
      echo "Token created. Export it for use:" >&2
      echo "  export OP_SERVICE_ACCOUNT_TOKEN='$token'" >&2
      ;;

    help|-h|--help)
      cat <<'HELP'
api - 1Password-backed API credential manager

Commands:
  api                       List all API Credential items in vault
  api get <name> [field]    Read a credential (default field: "credential")
  api set <name> <value>    Create or update an API Credential
  api del <name>            Delete a credential (with confirmation)
  api update                Regenerate ~/.zshrc_op_secrets from vault
  api token <vault> [hours] Generate a scoped service account token (default: 8h)
  api help                  Show this help

Environment:
  CREDENTIAL_PATTERN_VAULT    Vault to use (default: Personal)
  CREDENTIAL_PATTERN_SECRETS  Output file path (default: ~/.zshrc_op_secrets)

Conventions:
  - All items use category "API Credential" with a "credential" field
  - Tag items with "cli:<toolname>" to auto-generate `op run` aliases
  - Generated env vars use op:// references, resolved lazily by `op run`
HELP
      ;;

    *)
      # Default: list all API credentials
      op items list --vault="$CREDENTIAL_PATTERN_VAULT" --categories "API Credential"
      ;;
  esac
}

# Source the generated secrets file if it exists
[[ -f "$CREDENTIAL_PATTERN_SECRETS" ]] && source "$CREDENTIAL_PATTERN_SECRETS"
